import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { registerSW } from 'virtual:pwa-register'
import './index.css'
import './i18n.js'
import App from './App.jsx'

// Registers the Service Worker generated by vite-plugin-pwa
// with automatic reload upon background updates
registerSW({
  immediate: true,
  onNeedRefresh() {
    console.log('[PashuSetu PWA] New content available, reloading...')
    window.location.reload()
  },
  onOfflineReady() {
    console.log('[PashuSetu PWA] Application ready for offline triage')
  },
})

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)